-- ref.us_state_timezones
CREATE OR REPLACE TABLE `ref.us_state_timezones` (
  state_code STRING OPTIONS(description="USPS two-letter state code, e.g., FL, AZ."),
  tz_id      STRING OPTIONS(description="IANA time zone ID, e.g., America/New_York, America/Phoenix.")
)
OPTIONS(description="Raw mapping of US states to one or more IANA time zones. Source for representative tz selection.");

INSERT INTO ref.us_state_timezones (state_code, tz_id)
VALUES
  ('AL','America/Chicago'),
  ('AK','America/Anchorage'),
  ('AK','America/Adak'),
  ('AZ','America/Phoenix'),
  ('AR','America/Chicago'),
  ('CA','America/Los_Angeles'),
  ('CO','America/Denver'),
  ('CT','America/New_York'),
  ('DC','America/New_York'),
  ('DE','America/New_York'),
  ('FL','America/New_York'),
  ('FL','America/Chicago'),
  ('GA','America/New_York'),
  ('HI','Pacific/Honolulu'),
  ('IA','America/Chicago'),
  ('ID','America/Boise'),
  ('ID','America/Los_Angeles'),
  ('IL','America/Chicago'),
  ('IN','America/Indiana/Indianapolis'),
  ('IN','America/Chicago'),
  ('KS','America/Chicago'),
  ('KS','America/Denver'),
  ('KY','America/New_York'),
  ('KY','America/Chicago'),
  ('LA','America/Chicago'),
  ('MA','America/New_York'),
  ('MD','America/New_York'),
  ('ME','America/New_York'),
  ('MI','America/New_York'),
  ('MI','America/Chicago'),
  ('MN','America/Chicago'),
  ('MO','America/Chicago'),
  ('MS','America/Chicago'),
  ('MT','America/Denver'),
  ('NC','America/New_York'),
  ('ND','America/Chicago'),
  ('ND','America/Denver'),
  ('NE','America/Chicago'),
  ('NE','America/Denver'),
  ('NH','America/New_York'),
  ('NJ','America/New_York'),
  ('NM','America/Denver'),
  ('NV','America/Los_Angeles'),
  ('NV','America/Denver'),
  ('NY','America/New_York'),
  ('OH','America/New_York'),
  ('OK','America/Chicago'),
  ('OR','America/Los_Angeles'),
  ('OR','America/Boise'),
  ('PA','America/New_York'),
  ('RI','America/New_York'),
  ('SC','America/New_York'),
  ('SD','America/Chicago'),
  ('SD','America/Denver'),
  ('TN','America/Chicago'),
  ('TN','America/New_York'),
  ('TX','America/Chicago'),
  ('TX','America/Denver'),
  ('UT','America/Denver'),
  ('VA','America/New_York'),
  ('VT','America/New_York'),
  ('WA','America/Los_Angeles'),
  ('WI','America/Chicago'),
  ('WV','America/New_York'),
  ('WY','America/Denver');
